"""empty message

Revision ID: 4d467e0553f1
Revises: a70b1a5e08e9
Create Date: 2020-06-24 21:46:07.272623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d467e0553f1'
down_revision = 'a70b1a5e08e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('received_confirmations', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'user', ['email'], ['email'], ondelete='CASCADE')
    op.drop_column('transaction', 'recieved_confirmations')
    op.create_foreign_key(None, 'wallet', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.add_column('transaction', sa.Column('recieved_confirmations', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'received_confirmations')
    # ### end Alembic commands ###
