"""empty message

Revision ID: b02c7cf0ceff
Revises: 2f3ae5e7c606
Create Date: 2020-05-23 08:46:03.805393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b02c7cf0ceff'
down_revision = '2f3ae5e7c606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
