"""empty message

Revision ID: ff5024c150b7
Revises: 8e5a961e658f
Create Date: 2020-06-28 19:11:22.885927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff5024c150b7'
down_revision = '8e5a961e658f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('reference', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.add_column('transaction', sa.Column('amount', sa.DECIMAL(precision=20, scale=10), nullable=True))
    op.add_column('transaction', sa.Column('txn_from', sa.String(length=128), nullable=True))
    op.add_column('transaction', sa.Column('txn_to', sa.String(length=128), nullable=True))
    op.add_column('transaction', sa.Column('txn_type', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transaction', 'received_amount')
    op.drop_column('transaction', 'amount1')
    op.drop_column('transaction', 'amount2')
    op.create_foreign_key(None, 'wallet', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.add_column('transaction', sa.Column('amount2', mysql.DECIMAL(precision=20, scale=10), nullable=True))
    op.add_column('transaction', sa.Column('amount1', mysql.DECIMAL(precision=20, scale=10), nullable=True))
    op.add_column('transaction', sa.Column('received_amount', mysql.DECIMAL(precision=20, scale=10), nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'txn_type')
    op.drop_column('transaction', 'txn_to')
    op.drop_column('transaction', 'txn_from')
    op.drop_column('transaction', 'amount')
    op.drop_table('payment')
    # ### end Alembic commands ###
